Hosts:
  core-rest:     :38001
  invent-rest:   :38002
  core-event:   :38501
Connections:
  default:
    Txt: "postgres://rayi-user:PasswordRayi@localhost:5432/contohdb?sslmode=disable"
    PoolSize: 1000
    Timeout: 30
    UseTx: true
  rbac:
    Txt: "postgres://rayi-user:PasswordRayi@localhost:5432/contohdb?sslmode=disable"
    PoolSize: 1000
    Timeout: 30
    UseTx: true
  tenant:
    Txt: "postgres://rayi-user:PasswordRayi@localhost:5432/contohdb?sslmode=disable"
    PoolSize: 1000
    Timeout: 10
    UseTx: true
Services:
  core-rest:
    ServerType: Rest
    Provider: kaos-http-deployer
    Secret: "Strong_secret_2025"
    Timeout: 30
    ParamType: default-mux
    Data:
  invent-rest:
    ServerType: Rest
    Provider: kaos-http-deployer
    Secret: "Strong_secret_2025"
    Timeout: 30
    ParamType: default-mux
    Data:
  core-event:
    ServerType: Event
    Provider: event-http-deployer
    Secret: "Strong_secret_2025"
    Timeout: 30
    ParamType: func
    Data:
      require_validation: true
Data: 
  host_base_path: "http://localhost:38000"
  jwt_salt: "Strong_secret_2025"